CREATE DATABASE TESTE;

insert into tb_pedido (DT_PEDIDO,NR_PEDIDO,ID_TIPO_PEDIDO,ID_CLIENTE,ID_FORNECEDOR,ID_FILIAL,VL_TOTAL_PEDIDO) VALUES ('2020-02-25',1,1,1,1,6,300.00);

insert into tb_pedido (DT_PEDIDO,NR_PEDIDO,ID_TIPO_PEDIDO,ID_CLIENTE,ID_FORNECEDOR,ID_FILIAL,VL_TOTAL_PEDIDO) VALUES ('2020-02-26',2,2,4,3,10,459.34);

INSERT INTO TB_PEDIDO_NOTA (ID_PEDIDO,ID_NF) VALUES (1,1);

INSERT INTO TB_PEDIDO_NOTA (ID_PEDIDO,ID_NF) VALUES (2,2);